### ISSUE TITLE
Not Compiling in Flutter 3.0

### ISSUE THREAD

**Issue by kaumudpa** [pdliuw/ai_barcode#58]
```
e: /.pub-cache/hosted/pub.dartlang.org/ai_barcode-3.0.1/android/src/main/kotlin/com/air/ai_barcode/AndroidCreatorViewFactory.kt: (14, 1): Class 'AndroidCreatorViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /.pub-cache/hosted/pub.dartlang.org/ai_barcode-3.0.1/android/src/main/kotlin/com/air/ai_barcode/AndroidCreatorViewFactory.kt: (16, 5): 'create' overrides nothing
e: /.pub-cache/hosted/pub.dartlang.org/ai_barcode-3.0.1/android/src/main/kotlin/com/air/ai_barcode/AndroidScannerViewFactory.kt: (14, 1): Class 'AndroidScannerViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e:/.pub-cache/hosted/pub.dartlang.org/ai_barcode-3.0.1/android/src/main/kotlin/com/air/ai_barcode/AndroidScannerViewFactory.kt: (16, 5): 'create' overrides nothing
```

**Comment by kaumudpa** [comment]
@pdliuw any updates on this?

**Comment by hgtucel** [comment]
Yes, it doesn't compile in Flutter 3.0.

**Comment by kaumudpa** [comment]
Can somebody check and conform if the PR #59  this is working fine?

**Comment by niumj** [comment]
The same issue in Flutter 3.0。

**Comment by kaumudpa** [comment]
> The same issue in Flutter 3.0。

@niumj check PR #59
